### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by gunn4r** [iliasbhal/xstate-builder#9]
Hi! I am very interested in this higher level abstraction for xstate config....  it seems this repo has not been updated in a long time. Is there any plan to continue with this project?

**Comment by davidkpiano** [comment]
@gunn4r Just a note: there will eventually be official `xstate/builder` helper functions, which will be similar to this.

**Comment by gunn4r** [comment]
Heya @davidkpiano 👋 

Cool! I poked around a bit and didnt see an issue or anything for it (beyond some closed issues that reference this project basically).  Is this something just on your mental roadmap or is it tracked somewhere? I'd love to contribute.

**Comment by davidkpiano** [comment]
Tracked here: https://github.com/davidkpiano/xstate/projects/1#card-40599055

Tentative API: https://gist.github.com/davidkpiano/ae330406e630c63fe22022cdceb36f32

**Comment by gunn4r** [comment]
Perfect thank you! I love your dedication to this, it's somewhat infectious!
